//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCatalog.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookCatalog.Resources.Strings.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Something To Your Cart.
        /// </summary>
        public static string AddSomethingCart {
            get {
                return ResourceManager.GetString("AddSomethingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminArea.
        /// </summary>
        public static string AdminArea {
            get {
                return ResourceManager.GetString("AdminArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookCatalog.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKSCATALOG.
        /// </summary>
        public static string ApplicationTitleCAPS {
            get {
                return ResourceManager.GetString("ApplicationTitleCAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string BookPageTitle {
            get {
                return ResourceManager.GetString("BookPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Stores.
        /// </summary>
        public static string BookStoresPageTitle {
            get {
                return ResourceManager.GetString("BookStoresPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string CartPageTitle {
            get {
                return ResourceManager.GetString("CartPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, reload the application.
        /// </summary>
        public static string CatalogSummaryError {
            get {
                return ResourceManager.GetString("CatalogSummaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  We have an impressive collection of books existing out of {0} books, divided into {1} genres. We have books ranging in prices of {2} and {3}. Which makes the average price of our books {4}. All the {5} authors and {6} publishers are very happy to be in our collection. So there is a choice for everyone..
        /// </summary>
        public static string CatalogSummaryTemplate {
            get {
                return ResourceManager.GetString("CatalogSummaryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactPageTitle {
            get {
                return ResourceManager.GetString("ContactPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contactus {
            get {
                return ResourceManager.GetString("Contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryCode.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryName.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        public static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Books.
        /// </summary>
        public static string FeaturedBooks {
            get {
                return ResourceManager.GetString("FeaturedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureName.
        /// </summary>
        public static string FeatureName {
            get {
                return ResourceManager.GetString("FeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPageTitle.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutPageTitle {
            get {
                return ResourceManager.GetString("LogoutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Books Found.
        /// </summary>
        public static string NoBooks {
            get {
                return ResourceManager.GetString("NoBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Info About This Product.
        /// </summary>
        public static string NoInfoAboutThisProduct {
            get {
                return ResourceManager.GetString("NoInfoAboutThisProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items In Your Cart.
        /// </summary>
        public static string NoItemsCart {
            get {
                return ResourceManager.GetString("NoItemsCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reviews yet.
        /// </summary>
        public static string NoReviews {
            get {
                return ResourceManager.GetString("NoReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Placed Successfully!.
        /// </summary>
        public static string OrderPlaced {
            get {
                return ResourceManager.GetString("OrderPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Bookcatalog.
        /// </summary>
        public static string OurBookcatalog {
            get {
                return ResourceManager.GetString("OurBookcatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalCode.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Incl Tax:.
        /// </summary>
        public static string PriceInclTax {
            get {
                return ResourceManager.GetString("PriceInclTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍Search books....
        /// </summary>
        public static string SearchBooks {
            get {
                return ResourceManager.GetString("SearchBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍Search bookstores....
        /// </summary>
        public static string SearchBooksStores {
            get {
                return ResourceManager.GetString("SearchBooksStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubAdminArea.
        /// </summary>
        public static string SubAdminArea {
            get {
                return ResourceManager.GetString("SubAdminArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubLocality.
        /// </summary>
        public static string SubLocality {
            get {
                return ResourceManager.GetString("SubLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubThoroughfare.
        /// </summary>
        public static string SubThoroughfare {
            get {
                return ResourceManager.GetString("SubThoroughfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal:.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax:.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoroughfare.
        /// </summary>
        public static string Thoroughfare {
            get {
                return ResourceManager.GetString("Thoroughfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try adjusting your search.
        /// </summary>
        public static string TryAdjusting {
            get {
                return ResourceManager.GetString("TryAdjusting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webshop.
        /// </summary>
        public static string WebshopPageTitle {
            get {
                return ResourceManager.GetString("WebshopPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME TO OUR.
        /// </summary>
        public static string welcometoour {
            get {
                return ResourceManager.GetString("welcometoour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string YEmail {
            get {
                return ResourceManager.GetString("YEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string YMEssage {
            get {
                return ResourceManager.GetString("YMEssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string YName {
            get {
                return ResourceManager.GetString("YName", resourceCulture);
            }
        }
    }
}
